name: talenti_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # injector
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.1.2
  # Bloc
  bloc: ^8.1.1
  # Value equality
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1
  #import dio
  dio: ^5.1.1
  #animate rive
  rive: ^0.9.1
  #import flutter_svg
  flutter_svg: ^1.1.6
  #freezed functional programming
  freezed_annotation: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
flutter:
  uses-material-design: true
  assets:
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/
  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700